name : Analysis, Build and Publish Release

on:
  # Set this to be able to reuse workflows
  workflow_dispatch:
  push:
    branches:
      - main
      - CI/CD-Pipeline # TODO: to remove before merging to main

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  sonar:
    name: SonarQube analysis
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  build:
    needs: sonar
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests

  publish-release:
    needs: [sonar, build] # Ensure that the sonar Quality gates passed and the build job is completed before publishing the release
    permissions: write-all
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - run: mkdir staging && mv target/2048.jar target/2048-v1.0.${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "2048-v1.0.${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: staging/*.jar