name : Analysis, Build and Publish Release

on:
  # Set this to be able to reuse workflows
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  unit-testing:
    name: Unit Testing
    uses: ./.github/workflows/unit-testing.yml

  sonar:
    needs: unit-testing # Ensure that the unit tests passed before running the SonarQube analysis
    name: SonarQube analysis
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  build-publish-release:
    needs: sonar # Ensure that the sonar Quality gates passed before publishing the release
    permissions: write-all
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/2048.jar target/2048-v1.0.${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "2048-v1.0.${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: staging/*.jar