name: Complete Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  pull_request-naming:
    name: Pull request naming check
    uses: ./.github/workflows/Pull-request-naming.yml
  unit-testing:
    needs: pull_request-naming
    name: Unit Testing
    uses: ./.github/workflows/unit-testing.yml
    permissions: write-all
  lint:
    needs: unit-testing
    name: Lint using super-linter
    uses: ./.github/workflows/Lint.yml
    permissions:
      content: read
  commit-request-naming:
    needs: lint
    name: Conventional Commits
    uses: ./.github/workflows/Commit-request-naming.yml
  code-ql:
    needs: commit-request-naming
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql.yml
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read
  sonar:
    name: SonarQube Scan
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  build-publish-release:
    needs: sonar
    name: Build, Publish and release
    uses: ./.github/workflows/build-publish-release.yml
    permissions: write-all
  publish-javadoc:
    needs: build-publish-release
    name: Publish Javadoc
    uses: ./.github/workflows/publish-javadoc.yml
    permissions:
      contents: write
  deploy-website:
    needs: deploy-javadoc
    name: Deploy Website for javadoc
    uses: ./.github/workflows/deploy-website.yml
    permissions:
      contents: read
      pages: write
      id-token: write