name: Complete Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  pull_request-naming:
    runs-on: ubuntu-latest
    name: Pull request naming check
    uses: ./.github/workflows/Pull-request-naming.yml
  unit-testing:
    needs: pull_request-naming
    runs-on: ubuntu-latest
    name: Unit Testing
    uses: ./.github/workflows/unit-testing.yml
  lint:
    needs: unit-testing
    runs-on: ubuntu-latest
    name: Lint using super-linter
    uses: ./.github/workflows/Lint.yml
  commit-request-naming:
    needs: lint
    runs-on: ubuntu-latest
    name: Conventional Commits
    uses: ./.github/workflows/Commit-request-naming.yml
  code-ql:
    needs: commit-request-naming
    runs-on: ubuntu-latest
    name: CodeQL Analysis
    uses: ./.github/workflows/CodeQL.yml
  sonar:
    runs-on: ubuntu-latest
    name: SonarQube Scan
    uses: ./.github/workflows/SonarQube.yml
  build-publish-release:
    needs: sonar
    runs-on: ubuntu-latest
    name: Build, Publish and release
    uses: ./.github/workflows/build-publish-release.yml
  deploy-javadoc:
    needs: build-publish-release
    runs-on: ubuntu-latest
    name: Deploy Javadoc
    uses: ./.github/workflows/deploy-javadoc.yml
  deploy-website:
    needs: deploy-javadoc
    runs-on: ubuntu-latest
    name: Deploy Website for javadoc
    uses: ./.github/workflows/deploy-website.yml