name: Complete Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
  pull_request-naming:
    name: Pull request naming check
    uses: ./.github/workflows/Pull-request-naming.yml
  unit-testing:
    needs: pull_request-naming
    name: Unit Testing
    uses: ./.github/workflows/unit-testing.yml
#    permissions: write-all
  lint:
    needs: unit-testing
    name: Lint using super-linter
    uses: ./.github/workflows/Lint.yml
  commit-request-naming:
    needs: lint
    name: Conventional Commits
    uses: ./.github/workflows/Commit-request-naming.yml
  code-ql:
    needs: commit-request-naming
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql.yml
  sonar:
    name: SonarQube Scan
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  build-publish-release:
    needs: sonar
    name: Build, Publish and release
    uses: ./.github/workflows/build-publish-release.yml
  publish-javadoc:
    needs: build-publish-release
    name: Publish Javadoc
    uses: ./.github/workflows/publish-javadoc.yml
  deploy-website:
    needs: deploy-javadoc
    name: Deploy Website for javadoc
    uses: ./.github/workflows/deploy-website.yml