name: Pipeline Continuous Deployment

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Pipeline Continuous Integration"]
    types:
      - completed

permissions: write-all

jobs:
  publish-javadoc:
    name: Publish Javadoc
    uses: ./.github/workflows/publish-javadoc.yml
  deploy-website:
    needs: publish-javadoc
    name: Deploy Website for javadoc
    uses: ./.github/workflows/deploy-website.yml
  build-publish-release:
    needs: [publish-javadoc, deploy-website]
    name: Build, Publish and release
    uses: ./.github/workflows/build-publish-release.yml