name : Deploy & Release 2048 app

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
      - master
      - CI/CI-Pipeline  # TODO: to remove before merging to main

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  sonar:
    uses: ./.github/workflows/sonar.yml
    secrets: inherit

  build:
    permissions: write-all
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
      - run: mkdir staging && mv target/2048.jar target/2048-v1.0.${{ env.build-number }}.jar && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "2048-v1.0.${{ github.run_number }}"
          title: "Automated Build ${{ github.run_number }}"
          prerelease: true
          files: staging/*.jar