name: Lint using super-linter

on: [pull_request]
permissions:
  contents: read
  
jobs:
  fix-lint-issues:
    permissions:
      contents: write
      statuses: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          IGNORE_GITIGNORED_FILES: true
          FIX_GOOGLE_JAVA_FORMAT: true
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          

      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' &&  
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "fix(super-linter):linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
