name : Build & Deploy 2048 app

on :
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy the 2048 app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 22

      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
              context: .
              dockerfile: Dockerfile
              push: false #for now
              tags: ${{ secrets.DOCKER_USERNAME }}/2048:$(date-'%Y-%m-%d%H-%M-%S')
          
