name : Build & Deploy 2048 app

on :
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy the 2048 app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'open-jdk-22'
          java-version: 22

      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml
