name: Pipeline Execution Test

on:
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Check Pull Request"]
    types:
      - completed

permissions: write-all

jobs:
  unit-testing:
    name: Unit Testing
    uses: ./.github/workflows/unit-testing.yml
  lint:
    name: Lint using super-linter
    uses: ./.github/workflows/Lint.yml
  code-ql:
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql.yml
  sonar:
    name: SonarQube Scan
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
  publish-javadoc:
    needs: build-publish-release
    name: Publish Javadoc
    uses: ./.github/workflows/publish-javadoc.yml
  deploy-website:
    needs: publish-javadoc
    name: Deploy Website for javadoc
    uses: ./.github/workflows/deploy-website.yml
  build-publish-release:
    needs: [unit-testing, lint, code-ql, sonar, publish-javadoc, deploy-website]
    name: Build, Publish and release
    uses: ./.github/workflows/build-publish-release.yml