name: Check Pull Request
on:
  workflow_call: # Allows workflows to be reused by other workflows.
  pull_request: # Allows the workflow to be triggered on pull request events.
    types:
      - opened
      - edited
      - synchronize

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR target branch is ok
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "pr branch name: $branch_name"
          
          target_branch=${GITHUB_BASE_REF}
          echo "target branch: $target_branch"
          dev_regex="^(Closes|Bug|Feature|Hotfix|Experiment)/"
          
          if [[ "$branch_name" =~ $dev_regex ]]; then
            echo "Branch name matches the first regex pattern."
            
            
          
          else
            echo "Branch name does not match any regex. Exiting..."
            exit 1
          fi
        shell: bash
